server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
