CREATE TABLE IF NOT EXISTS address (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        region VARCHAR(255) NOT NULL,
        city VARCHAR(255) NOT NULL,
        street VARCHAR(255) NOT NULL,
        house VARCHAR(50) NOT NULL,
        apartment VARCHAR(50)
    );

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    birth_date DATE NOT NULL,
    address_id BIGINT,

        FOREIGN KEY (address_id) REFERENCES address(id) ON DELETE SET NULL
    );

CREATE INDEX idx_users_first_name ON users(first_name);
CREATE INDEX idx_users_last_name ON users(last_name);
CREATE INDEX idx_users_middle_name ON users(middle_name);

CREATE INDEX idx_address_region ON address(region);
CREATE INDEX idx_address_city ON address(city);
CREATE INDEX idx_address_street ON address(street);

CREATE INDEX idx_users_address_id ON users(address_id);